name: Awake

on:
  repository_dispatch:
    types: [wake]

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - run: /opt/theo/wake.sh "${{ github.event.client_payload.prompt }}"
